plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

baseurl: "" # the subpath of the site, e.g. /blog
url: "" # the base hostname & protocol for the site, e.g. http://example.com


theme: jekyll-theme-slate